version: 2
# Thanks to https://github.com/calmery/elm-boilerplate
jobs:
  setup:
    docker:
      - image: circleci/node:10.16.0

    working_directory: ~/elm

    steps:
      - checkout

      - restore_cache:
          keys:
            - elm-0.19-node_modules-dependencies-{{ checksum "package.json" }}

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: elm-0.19-node_modules-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/
          paths: ./*

  lint:
    docker:
      - image: circleci/node:10.16.0

    working_directory: ~/elm

    steps:
      - attach_workspace:
          at: ~/

      - restore_cache:
          keys:
            - elm-0.19-dependencies-{{ checksum "elm.json" }}

      - run: yarn elm-format --validate

      - save_cache:
          paths:
            - elm-stuff
            - ~/.elm
          key: elm-0.19-dependencies-{{ checksum "elm.json" }}

      - persist_to_workspace:
          root: ~/
          paths: ./*

  test:
    docker:
      - image: circleci/node:10.16.0

    working_directory: ~/elm

    steps:
      - attach_workspace:
          at: ~/

      - restore_cache:
          keys:
            - elm-0.19-dependencies-{{ checksum "elm.json" }}

      - run: yarn test

      - save_cache:
          paths:
            - elm-stuff
            - ~/.elm
          key: elm-0.19-dependencies-{{ checksum "elm.json" }}

      - persist_to_workspace:
          root: ~/
          paths: ./*

  build dev:
    docker:
      - image: circleci/node:10.16.0

    working_directory: ~/elm

    steps:
      - attach_workspace:
          at: ~/

      - run: yarn build --no-minify


workflows:
  version: 2

  lint-test-and-build:
    jobs:
      - setup

      - lint:
          requires:
            - setup

      - test:
          requires:
            - lint

      - build dev:
          requires:
            - test
